[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[font]
size = 15.0

[font.normal]
family = "VictorMono"
style = "SemiBold"

[terminal]
shell = { program = "/bin/fish" }
